image: Visual Studio 2022

environment:
  PY_PYTHON: "3.11"

cache:
  - '%LOCALAPPDATA%\pip\Cache'

install:
  - py -3 --version
  - py -3 -m pip install --upgrade pip
  - py -3 -m pip install requests gmssl pyinstaller

build_script:
  - py -3 -m PyInstaller --onefile --windowed --name "GulfSign" --clean --noconfirm --hidden-import gmssl --hidden-import gmssl.sm4 --hidden-import gmssl.sm3 --hidden-import gmssl.func --add-data "hc_api.py;." app.py
  - dir dist

artifacts:
  - path: dist\GulfSign.exe
    name: GulfSign
    type: file

deploy: off
